@ECHO OFF
set ADSK_3DSMAX_x64_2013=C:\Program Files\Autodesk\3ds Max 2013\
set ADSK_3DSMAX_x64_2014=C:\Program Files\Autodesk\3ds Max 2014\
set ADSK_3DSMAX_x64_2016=C:\Program Files\Autodesk\3ds Max 2016\
set ALLUSERSPROFILE=C:\ProgramData
set APPDATA=C:\Users\Анатолий\AppData\Roaming
set CommonProgramFiles=C:\Program Files\Common Files
set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
set CommonProgramW6432=C:\Program Files\Common Files
set COMPUTERNAME=ANATOLY
set ComSpec=C:\Windows\system32\cmd.exe
set configsetroot=C:\Windows\ConfigSetRoot
set CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5
set CUDA_PATH_V6_5=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5
set DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\
set ESET_OPTIONS=                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
set FP_NO_HOST_CHECK=NO
set HOMEDRIVE=C:
set HOMEPATH=\Users\Анатолий
set KMP_DUPLICATE_LIB_OK=TRUE
set LOCALAPPDATA=C:\Users\Анатолий\AppData\Local
set LOGONSERVER=\\ANATOLY
set MKL_SERIAL=YES
set MSBuildLoadMicrosoftTargetsReadOnly=true
set NUMBER_OF_PROCESSORS=4
set NVCUDASAMPLES6_5_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v6.5
set NVCUDASAMPLES_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v6.5
set NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
set OS=Windows_NT
set Path=C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\libnvvp;C:\PROGRA~2\Borland\CBUILD~1\Bin;C:\PROGRA~2\Borland\CBUILD~1\Projects\Bpl;C:\Program Files (x86)\Borland\Delphi7\Bin;C:\Program Files (x86)\Borland\Delphi7\Projects\Bpl\;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files\Common Files\Autodesk Shared\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Autodesk\Backburner\
set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
set PkgDefApplicationConfigFile=C:\Users\Анатолий\AppData\Local\Microsoft\VisualStudio\11.0\devenv.exe.config
set PROCESSOR_ARCHITECTURE=AMD64
set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
set PROCESSOR_LEVEL=6
set PROCESSOR_REVISION=2a07
set ProgramData=C:\ProgramData
set ProgramFiles=C:\Program Files
set ProgramFiles(x86)=C:\Program Files (x86)
set ProgramW6432=C:\Program Files
set PROMPT=$P$G
set PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
set PUBLIC=C:\Users\Public
set SESSIONNAME=Console
set str="c:\cuda\fractal 04.07.15\drawer2d\drawer2d.cpp.cl.cmd"
set SystemDrive=C:
set SystemRoot=C:\Windows
set TEMP=C:\Users\E393~1\AppData\Local\Temp
set TMP=C:\Users\E393~1\AppData\Local\Temp
set USERDOMAIN=Anatoly
set USERNAME=Анатолий
set USERPROFILE=C:\Users\Анатолий
set VBROKERDIR=C:\Inprise\vbroker
set VisualStudioDir=C:\Users\Анатолий\Documents\Visual Studio 2012
set VisualStudioEdition=Microsoft Visual Studio Ultimate 2012
set VisualStudioVersion=11.0
set VS110COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
set VS120COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
set VS80COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\Tools\
set VSLANG=1033
set VSSDK120Install=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VSSDK\
set windir=C:\Windows
set XNAGSShared=C:\Program Files (x86)\Common Files\Microsoft Shared\XNA\
set XNAGSv4=C:\Program Files (x86)\Microsoft XNA\XNA Game Studio\v4.0\
@call "c:\program files (x86)\pvs-studio\x86\clang.exe" @"Drawer2D.cpp_CLANG_9660.CLMonitoring.bat.rsp" 2>&1
